### ISSUE TITLE
este enum puede ir dentro de pedido

### ISSUE THREAD

**Issue by maurociancio** [LGhosn/TakeAwayNow-DCNT#11]
package com.dcnt.take_away_now.enums;
public enum EstadoDelPedido {
    AGUARDANDO_PREPARACION,
    EN_PREPARACION,
    LISTO_PARA_RETIRAR,
    RETIRADO,
    CANCELADO,
    DEVOLUCION_SOLICITADA,
    DEVOLUCION_ACEPTADA,
    DEVOLUCION_DENEGADA
}

como un inner enum

**Comment by ruizsugliani** [comment]
Perfecto, ahí lo cambiamos, gracias por la observación.
