### ISSUE TITLE
si ignoras warnings, poner xq?

### ISSUE THREAD

**Issue by maurociancio** [LGhosn/TakeAwayNow-DCNT#14]

**Comment by maurociancio** [comment]
@SuppressWarnings("OptionalGetWithoutIsPresent")

**Comment by maurociancio** [comment]
sino es dudoso

**Comment by ruizsugliani** [comment]
Se quitaron esas annotation donde estaban de más, solo quedó en una que antes del get() se valida la existencia del registro.
